### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pepijnolivier** [Cysha/casino-holdem#2]
Hi there,

Interested in using this package.
Code seems clean!

Would you mind making a "getting up & running" example doc on how to set up a new Game between 3 players ?

**Comment by xLink** [comment]
hey @pepijnolivier, 

Unfortunately the only documentation this thing has for now is the tests. Not ideal, I know, but never the less, this should help:
https://github.com/Cysha/casino-holdem/blob/master/tests/Game/PlayerButtonTest.php#L133

any thoughts @NoelDavies ?

**Comment by pepijnolivier** [comment]
@xLink Thanks for the tip ! I should be able to get started with this

**Comment by xLink** [comment]
np @pepijnolivier feel free to spawn any issues you might come across!
