### ISSUE TITLE
Multiplayer game ?

### ISSUE THREAD

**Issue by zilveer** [Cysha/casino-holdem#3]
Hi,
Is this a multiplayer holdem game ?

Regards

**Comment by xLink** [comment]
It can be used to develop a multiplayer game, yes.

**Comment by zilveer** [comment]
@xLink
Thanks for your response.
Is there any UI coding in your plans ?

Regards

**Comment by xLink** [comment]
That isn't in the scope of this library.

**Comment by zilveer** [comment]
@xLink I understand, thanks for a quick reply.
But can you please guide me of how I can use this or how it is used?

**Comment by xLink** [comment]
It is setup to provide game logic already, you need to read through the code and figure out how to best incorperate it into your system, the library on its own won't do anything.
