### ISSUE TITLE
How to get available buttons for the current turn?

### ISSUE THREAD

**Issue by ammarfaizi2** [Cysha/casino-holdem#4]
Hi, I am implementing this package to a web game and having an issue with available button for the current turn.

Is there any way to get the available buttons (actions) after use `whoTurnsIsIt` method?

Or must I predict myself based on the round and game condition?

Thank you in advance.

**Comment by NoelDavies** [comment]
On the round, you should be able to fetch these from `src/Game/Round.php` and use `->actions()`. You can then do a filter based on the user

**Comment by ammarfaizi2** [comment]
Thanks!
